/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import java.util.List;

/**
 *
 * @author avbravo
 */
@Entity()
public class Appmoduleconfiguration {

    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idappmoduleconfiguration;
    @Column
    private Boolean active;

    @Referenced(from = "applicative", localField = "idapplicative")
    private Applicative applicative;
    
    @Referenced(from = "role", localField = "idrole")
    private List<Role> role;

    @Column
    private String event;

    @Column
    private String module;

  
    
    
  
    

    public Appmoduleconfiguration() {
    }

    public Appmoduleconfiguration(Long idappmoduleconfiguration, Boolean active, Applicative applicative, List<Role> role, String event, String module) {
        this.idappmoduleconfiguration = idappmoduleconfiguration;
        this.active = active;
        this.applicative = applicative;
        this.role = role;
        this.event = event;
        this.module = module;
    }

   
    

    public Long getIdappmoduleconfiguration() {
        return idappmoduleconfiguration;
    }

    public void setIdappmoduleconfiguration(Long idappmoduleconfiguration) {
        this.idappmoduleconfiguration = idappmoduleconfiguration;
    }

   

  
    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Applicative getApplicative() {
        return applicative;
    }

    public void setApplicative(Applicative applicative) {
        this.applicative = applicative;
    }

    public String getEvent() {
        return event;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public String getModule() {
        return module;
    }

    public void setModule(String module) {
        this.module = module;
    }

    public List<Role> getRole() {
        return role;
    }

    public void setRole(List<Role> role) {
        this.role = role;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Appmoduleconfiguration{");
        sb.append("idappmoduleconfiguration=").append(idappmoduleconfiguration);
        sb.append(", active=").append(active);
        sb.append(", applicative=").append(applicative);
        sb.append(", role=").append(role);
        sb.append(", event=").append(event);
        sb.append(", module=").append(module);
        sb.append('}');
        return sb.toString();
    }

   
   

    

}
