/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;

/**
 *
 * @author avbravo
 */
@Entity()
public class Building {

    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idbuilding;

    @Referenced(from = "headquarter", localField = "idheadquarter")
    private Headquarter headquarter;

    @Column
    private Boolean active;
    @Column
    private String building;

    @Column
    private String shortname;

    public Building() {
    }

    public Building(Long idbuilding, Boolean active, String building, Headquarter headquarter, String shortname) {
        this.idbuilding = idbuilding;
        this.active = active;
        this.building = building;
        this.headquarter = headquarter;
        this.shortname = shortname;
    }

    public Long getIdbuilding() {
        return idbuilding;
    }

    public void setIdbuilding(Long idbuilding) {
        this.idbuilding = idbuilding;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public String getBuilding() {
        return building;
    }

    public void setBuilding(String building) {
        this.building = building;
    }

    public Headquarter getHeadquarter() {
        return headquarter;
    }

    public void setHeadquarter(Headquarter headquarter) {
        this.headquarter = headquarter;
    }

    public String getShortname() {
        return shortname;
    }

    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Building{");
        sb.append("idbuilding=").append(idbuilding);
        sb.append(", active=").append(active);
        sb.append(", building=").append(building);
        sb.append(", headquarter=").append(headquarter);
        sb.append(", shortname=").append(shortname);
        sb.append('}');
        return sb.toString();
    }

}
