/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;

/**
 *
 * @author avbravo
 */
@Entity
public class Grupo {
    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idgrupo;
    @Column
    private String grupo;
    @Column
    private Boolean active;

    public Grupo() {
    }

    public Grupo(Long idgrupo, String grupo, Boolean active) {
        this.idgrupo = idgrupo;
        this.grupo = grupo;
        this.active = active;
    }

    public Long getIdgrupo() {
        return idgrupo;
    }

    public void setIdgrupo(Long idgrupo) {
        this.idgrupo = idgrupo;
    }

    public String getGrupo() {
        return grupo;
    }

    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Grupo{");
        sb.append("idgrupo=").append(idgrupo);
        sb.append(", grupo=").append(grupo);
        sb.append(", active=").append(active);
        sb.append('}');
        return sb.toString();
    }
    
    
    
}
