/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;

/**
 *
 * @author avbravo
 */
@Entity
public class Icono {
@Id(autogeneratedActive = AutogeneratedActive.ON)
private Long idicono;
@Column
private String icono;

    public Icono() {
    }

    public Icono(Long idicono, String icono) {
        this.idicono = idicono;
        this.icono = icono;
    }

    public Long getIdicono() {
        return idicono;
    }

    public void setIdicono(Long idicono) {
        this.idicono = idicono;
    }

    public String getIcono() {
        return icono;
    }

    public void setIcono(String icono) {
        this.icono = icono;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Icono{");
        sb.append("idicono=").append(idicono);
        sb.append(", icono=").append(icono);
        sb.append('}');
        return sb.toString();
    }



}
