/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;

/**
 *
 * @author avbravo
 */
@Entity
public class Institution {
   @Id(autogeneratedActive = AutogeneratedActive.ON)
  private Long idinstitution;
   @Column
   private String institution;
   
   @Column
   private Boolean active;

    public Institution() {
    }

    public Institution(Long idinstitution, String institution, Boolean active) {
        this.idinstitution = idinstitution;
        this.institution = institution;
        this.active = active;
    }

    public Long getIdinstitution() {
        return idinstitution;
    }

    public void setIdinstitution(Long idinstitution) {
        this.idinstitution = idinstitution;
    }

    public String getInstitution() {
        return institution;
    }

    public void setInstitution(String institution) {
        this.institution = institution;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }


}
