/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import java.util.Date;

/**
 *
 * @author avbravo
 */
@Entity()
public class Otp {

    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idotp;
    @Column
    private Date expirationdate;

    @Column
    private Long iduser;
    @Column
    private Boolean isexpired;
    @Column
    private Integer otp;
    @Column
    private Boolean used;

    public Otp() {
    }

    public Otp(Date expirationdate, Long idotp, Long iduser, Boolean isexpired, Integer otp, Boolean used) {
        this.expirationdate = expirationdate;
        this.idotp = idotp;
        this.iduser = iduser;
        this.isexpired = isexpired;
        this.otp = otp;
        this.used = used;
    }

    public Date getExpirationdate() {
        return expirationdate;
    }

    public void setExpirationdate(Date expirationdate) {
        this.expirationdate = expirationdate;
    }

    public Long getIdotp() {
        return idotp;
    }

    public void setIdotp(Long idotp) {
        this.idotp = idotp;
    }

    public Long getIduser() {
        return iduser;
    }

    public void setIduser(Long iduser) {
        this.iduser = iduser;
    }

    public Boolean getIsexpired() {
        return isexpired;
    }

    public void setIsexpired(Boolean isexpired) {
        this.isexpired = isexpired;
    }

    public Integer getOtp() {
        return otp;
    }

    public void setOtp(Integer otp) {
        this.otp = otp;
    }

    public Boolean getUsed() {
        return used;
    }

    public void setUsed(Boolean used) {
        this.used = used;
    }

}
