/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;

/**
 *
 * @author avbravo
 */
@Entity()
public class Province {

    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idprovince;
    @Column
    private Boolean active;
    @Referenced(from = "country", localField = "idcountry")
    private Country country;

    @Column
    private String province;

    public Province() {
    }

    public Province(Long idprovince, Boolean active, Country country, String province) {
        this.idprovince = idprovince;
        this.active = active;
        this.country = country;
        this.province = province;
    }

    public Long getIdprovince() {
        return idprovince;
    }

    public void setIdprovince(Long idprovince) {
        this.idprovince = idprovince;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Country getCountry() {
        return country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Province{");
        sb.append("idprovince=").append(idprovince);
        sb.append(", active=").append(active);
        sb.append(", country=").append(country);
        sb.append(", province=").append(province);
        sb.append('}');
        return sb.toString();
    }
    
    
    

}
