/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Embedded;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import java.util.Date;
import java.util.List;

/**
 *
 * @author avbravo
 */
@Entity
public class Proyecto {

    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idproyecto;
    @Column
    private String proyecto;
    
    @Column
    private Integer anio;
    @Column
    private String descripcion;
    @Column
    private Date fechafinal;
    @Column
    private Date fechainicial;
    
    @Referenced(from = "Icono", localField = "idicono")
    private Icono icono;
    @Referenced(from = "departament", localField = "iddepartament")
    List<Departament> departament;

    @Embedded
    List<Requisito> requisito;

    @Referenced(from = "user", localField = "iduser")
    List<User> user;

    @Column
    private Double avance;

    @Column
    private String estado;
    @Column
    private Boolean active;

    public Proyecto() {
    }

    public Proyecto(Long idproyecto, String proyecto, Integer anio, String descripcion, Date fechafinal, Date fechainicial, Icono icono, List<Departament> departament, List<Requisito> requisito, List<User> user, Double avance, String estado, Boolean active) {
        this.idproyecto = idproyecto;
        this.proyecto = proyecto;
        this.anio = anio;
        this.descripcion = descripcion;
        this.fechafinal = fechafinal;
        this.fechainicial = fechainicial;
        this.icono = icono;
        this.departament = departament;
        this.requisito = requisito;
        this.user = user;
        this.avance = avance;
        this.estado = estado;
        this.active = active;
    }

    
    
    
    public Icono getIcono() {
        return icono;
    }

    public void setIcono(Icono icono) {
        this.icono = icono;
    }

    
    public Long getIdproyecto() {
        return idproyecto;
    }

    public void setIdproyecto(Long idproyecto) {
        this.idproyecto = idproyecto;
    }

    public Integer getAnio() {
        return anio;
    }

    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    public List<Departament> getDepartament() {
        return departament;
    }

    public void setDepartament(List<Departament> departament) {
        this.departament = departament;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Date getFechafinal() {
        return fechafinal;
    }

    public void setFechafinal(Date fechafinal) {
        this.fechafinal = fechafinal;
    }

    public Date getFechainicial() {
        return fechainicial;
    }

    public void setFechainicial(Date fechainicial) {
        this.fechainicial = fechainicial;
    }

    public String getProyecto() {
        return proyecto;
    }

    public void setProyecto(String proyecto) {
        this.proyecto = proyecto;
    }

    public List<Requisito> getRequisito() {
        return requisito;
    }

    public void setRequisito(List<Requisito> requisito) {
        this.requisito = requisito;
    }

    public List<User> getUser() {
        return user;
    }

    public void setUser(List<User> user) {
        this.user = user;
    }

    public Double getAvance() {
        return avance;
    }

    public void setAvance(Double avance) {
        this.avance = avance;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Proyecto{");
        sb.append("idproyecto=").append(idproyecto);
        sb.append(", proyecto=").append(proyecto);
        sb.append(", anio=").append(anio);
        sb.append(", descripcion=").append(descripcion);
        sb.append(", fechafinal=").append(fechafinal);
        sb.append(", fechainicial=").append(fechainicial);
        sb.append(", icono=").append(icono);
        sb.append(", departament=").append(departament);
        sb.append(", requisito=").append(requisito);
        sb.append(", user=").append(user);
        sb.append(", avance=").append(avance);
        sb.append(", estado=").append(estado);
        sb.append(", active=").append(active);
        sb.append('}');
        return sb.toString();
    }

    

}
