/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;

/**
 *
 * @author avbravo
 */
@Entity
public class Role {

    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idrole;
    @Column
    private Boolean active;

    @Column
    private String role;

    public Role() {
    }

    public Role(Long idrole, Boolean active, String role) {
        this.idrole = idrole;
        this.active = active;
        this.role = role;
    }

    public Long getIdrole() {
        return idrole;
    }

    public void setIdrole(Long idrole) {
        this.idrole = idrole;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Role{");
        sb.append("idrole=").append(idrole);
        sb.append(", active=").append(active);
        sb.append(", role=").append(role);
        sb.append('}');
        return sb.toString();
    }
    
    
    
}
