/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import java.util.Date;

/**
 *
 * @author avbravo
 */
@Entity
public class Sprint {



    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idsprint;
    @Column
    private String sprint;
    @Column
    private String descripcion;
    @Column
    private Date fechafinal;
    @Column
    private Date fechainicial;
    @Column
    private Boolean open;

    @Referenced(from = "proyecto", localField = "idproyecto")
    Proyecto proyecto;
    @Column
    private Boolean active;

    public Sprint() {
    }

    public Sprint(Long idsprint, String sprint, String descripcion, Date fechafinal, Date fechainicial, Boolean open, Proyecto proyecto, Boolean active) {
        this.idsprint = idsprint;
        this.sprint = sprint;
        this.descripcion = descripcion;
        this.fechafinal = fechafinal;
        this.fechainicial = fechainicial;
        this.open = open;
        this.proyecto = proyecto;
        this.active = active;
    }

   

    
    
    
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    
    
    
    public Long getIdsprint() {
        return idsprint;
    }

    public void setIdsprint(Long idsprint) {
        this.idsprint = idsprint;
    }

    public String getSprint() {
        return sprint;
    }

    public void setSprint(String sprint) {
        this.sprint = sprint;
    }

    public Boolean getOpen() {
        return open;
    }

    public void setOpen(Boolean open) {
        this.open = open;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Date getFechafinal() {
        return fechafinal;
    }

    public void setFechafinal(Date fechafinal) {
        this.fechafinal = fechafinal;
    }

    public Date getFechainicial() {
        return fechainicial;
    }

    public void setFechainicial(Date fechainicial) {
        this.fechainicial = fechainicial;
    }

    public Proyecto getProyecto() {
        return proyecto;
    }

    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Sprint{");
        sb.append("idsprint=").append(idsprint);
        sb.append(", sprint=").append(sprint);
        sb.append(", descripcion=").append(descripcion);
        sb.append(", fechafinal=").append(fechafinal);
        sb.append(", fechainicial=").append(fechainicial);
        sb.append(", open=").append(open);
        sb.append(", proyecto=").append(proyecto);
        sb.append(", active=").append(active);
        sb.append('}');
        return sb.toString();
    }

    

}
