/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.sft.model.Actividad;
import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;

/**
 *
 * @author avbravo
 */
@Entity
public class Subactividad {

    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idsubactividad;
    @Column
    private String codigo;
    @Column
    private String subactividad;
    @Column
    private Integer anio;
    @Column
    private Boolean active;

    @Referenced(from = "actividad", localField = "idactividad")
    Actividad actividad;

    public Subactividad() {
    }

    public Subactividad(Long idsubactividad, String codigo, String subactividad, Integer anio, Boolean active, Actividad actividad) {
        this.idsubactividad = idsubactividad;
        this.codigo = codigo;
        this.subactividad = subactividad;
        this.anio = anio;
        this.active = active;
        this.actividad = actividad;
    }

    public Long getIdsubactividad() {
        return idsubactividad;
    }

    public void setIdsubactividad(Long idsubactividad) {
        this.idsubactividad = idsubactividad;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getSubactividad() {
        return subactividad;
    }

    public void setSubactividad(String subactividad) {
        this.subactividad = subactividad;
    }

    public Integer getAnio() {
        return anio;
    }

    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Actividad getActividad() {
        return actividad;
    }

    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Subactividad{");
        sb.append("idsubactividad=").append(idsubactividad);
        sb.append(", codigo=").append(codigo);
        sb.append(", subactividad=").append(subactividad);
        sb.append(", anio=").append(anio);
        sb.append(", active=").append(active);
        sb.append(", actividad=").append(actividad);
        sb.append('}');
        return sb.toString();
    }
    
    
    

}
