/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.ViewEntity;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import java.util.Date;

/**
 *
 * @author avbravo
 */
@ViewEntity(collection = "tarjeta")
public class TarjetaView {

    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idtarjeta;
    @Column
    private String tarjeta;
    @Column
    private String descripcion;

  
    @Column
    private Date fechainicial;
    @Column
    private Date fechafinal;

    @Column
    private String prioridad;

    @Column
    private String estimacion;
      @Column
    private Boolean active;
    
    @Column
    private Long idrequisito;
 

    @Column
    private String columna;
    
    
  

    public TarjetaView() {
    }

    public TarjetaView(Long idtarjeta, String tarjeta, String descripcion, Date fechainicial, Date fechafinal, String prioridad, String estimacion, Boolean active, Long idrequisito, String columna) {
        this.idtarjeta = idtarjeta;
        this.tarjeta = tarjeta;
        this.descripcion = descripcion;
        this.fechainicial = fechainicial;
        this.fechafinal = fechafinal;
        this.prioridad = prioridad;
        this.estimacion = estimacion;
        this.active = active;
        this.idrequisito = idrequisito;
        this.columna = columna;
    }

    
    
    public Long getIdtarjeta() {
        return idtarjeta;
    }

    public void setIdtarjeta(Long idtarjeta) {
        this.idtarjeta = idtarjeta;
    }

    public String getTarjeta() {
        return tarjeta;
    }

    public void setTarjeta(String tarjeta) {
        this.tarjeta = tarjeta;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Date getFechainicial() {
        return fechainicial;
    }

    public void setFechainicial(Date fechainicial) {
        this.fechainicial = fechainicial;
    }

    public Date getFechafinal() {
        return fechafinal;
    }

    public void setFechafinal(Date fechafinal) {
        this.fechafinal = fechafinal;
    }

    public String getPrioridad() {
        return prioridad;
    }

    public void setPrioridad(String prioridad) {
        this.prioridad = prioridad;
    }

    public String getEstimacion() {
        return estimacion;
    }

    public void setEstimacion(String estimacion) {
        this.estimacion = estimacion;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Long getIdrequisito() {
        return idrequisito;
    }

    public void setIdrequisito(Long idrequisito) {
        this.idrequisito = idrequisito;
    }

    public String getColumna() {
        return columna;
    }

    public void setColumna(String columna) {
        this.columna = columna;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("TarjetaView{");
        sb.append("idtarjeta=").append(idtarjeta);
        sb.append(", tarjeta=").append(tarjeta);
        sb.append(", descripcion=").append(descripcion);
        sb.append(", fechainicial=").append(fechainicial);
        sb.append(", fechafinal=").append(fechafinal);
        sb.append(", prioridad=").append(prioridad);
        sb.append(", estimacion=").append(estimacion);
        sb.append(", active=").append(active);
        sb.append(", idrequisito=").append(idrequisito);
        sb.append(", columna=").append(columna);
        sb.append('}');
        return sb.toString();
    }

  
   
    

    
    
}
