/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;

/**
 *
 * @author avbravo
 */
@Entity()
public class Township {
    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idtownship;
    @Column
    private String township;
    @Column
    private Boolean active;
    
    @Referenced(from = "district", localField = "iddistrict")
    private District district; 

    public Township() {
    }

    public Township(Long idtownship, String township, Boolean active, District district) {
        this.idtownship = idtownship;
        this.township = township;
        this.active = active;
        this.district = district;
    }

    public Long getIdtownship() {
        return idtownship;
    }

    public void setIdtownship(Long idtownship) {
        this.idtownship = idtownship;
    }

    public String getTownship() {
        return township;
    }

    public void setTownship(String township) {
        this.township = township;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public District getDistrict() {
        return district;
    }

    public void setDistrict(District district) {
        this.district = district;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Township{");
        sb.append("idtownship=").append(idtownship);
        sb.append(", township=").append(township);
        sb.append(", active=").append(active);
        sb.append(", district=").append(district);
        sb.append('}');
        return sb.toString();
    }
  
    

 
}
