/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sft.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;

/**
 *
 * @author avbravo
 */
@Entity()
public class Zone {
      @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idzone;
    @Column
    private Boolean active;
    
    @Referenced(from = "building", localField = "idbuilding")
    private Building building;
    @Column
    private String descripcion;
    @Column
    private String icon;
  
    @Column
    private String zone;

    public Zone() {
    }

    public Zone(Long idzone, Boolean active, Building building, String descripcion, String icon, String zone) {
        this.idzone = idzone;
        this.active = active;
        this.building = building;
        this.descripcion = descripcion;
        this.icon = icon;
        this.zone = zone;
    }

    public Long getIdzone() {
        return idzone;
    }

    public void setIdzone(Long idzone) {
        this.idzone = idzone;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Building getBuilding() {
        return building;
    }

    public void setBuilding(Building building) {
        this.building = building;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getZone() {
        return zone;
    }

    public void setZone(String zone) {
        this.zone = zone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Zone{");
        sb.append("idzone=").append(idzone);
        sb.append(", active=").append(active);
        sb.append(", building=").append(building);
        sb.append(", descripcion=").append(descripcion);
        sb.append(", icon=").append(icon);
        sb.append(", zone=").append(zone);
        sb.append('}');
        return sb.toString();
    }

    
    
    
}
